### ISSUE TITLE
beef up the tests

### ISSUE THREAD

**Issue by aric87** [chieakiba/oinkster#4]
You should test each endpoint for every possible situation. What if there's a request with no data? What if the contact is already stored in SendGrid?  This is a good app to show off that you're thinking about testing lots of possible outcomes for each route (especially since there are only two routes, it shouldn't be too terrible)

**Comment by chieakiba** [comment]
It seems like Sendgrid doesn't create duplicate contacts in their contact database. They usually overwrite it (I've tested it out before and this seems to be the case). Per your suggestion, I made the email address unique so if someone does update it their email it automatically does that on Sendgrid's end. Also I made it so that the user has to fill out all the fields to submit. The submit button is disabled until the user fills out all the fields so I think that's fine. Unless there's another way the user can do that?
